#!/usr/bin/env bash
# ============================================================
# RFAA-Cpp remote server FULL_TRAIN training script
# Usage: bash remote_fulltrain.sh
# Overview:
#   1. Stage 1: single sample P04637 (with templates P04637_template_coords/ + P04637_pdbs/ true coords)
#      [skipped by default] SKIP_P04637=1 (2026-08-28: high memory peak, skipped for now; set SKIP_P04637=0 to run)
#   2. Stage 2: multi-sample (PPML_MULTI_SAMPLE=1, dataset default = training_batch_data_le103,
#      contains only L<=103 samples: P62805(L=103) + P62891(L=51), keeps the pair-track memory peak bounded)
#   3. Log: remote_fulltrain_YYYYMMDD_HHMMSS.log
# Env overrides: FULL_TRAIN(default true) PPML_NUM_EPOCHS(default 10) PPML_LR(default 1e-4)
#                PPML_CLIP_NORM(default 0.1) PPML_ACCUM(default 4) PPML_MSA_DEPTH(global default 512)
#                PPML_MULTI_MSA_DEPTH(stage 2 MSA depth, **default 256**; stage 1 fixed 256)
#                PPML_CUDA_NO_SCATTER(default 1, scatter falls back to CPU for reliable mixed training)
#                SKIP_P04637(default 1) PPML_DATASET_DIR(default training_batch_data_le103)
# Progress: neither stage has a timeout, training ends naturally. Live progress:
#   tail -f remote_fulltrain_*.log  and watch 'Epoch N/M completed ... loss:' lines;
#   if no output for a long time, check whether '[FWD-GRAPH] ... build ...' was printed (slow first full-size build is normal).
# ============================================================
set -u

# ---------- 0. Server environment paths ----------
# Project root: default is the directory of this script (project root), override via RFAA_PROJ
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJ="${RFAA_PROJ:-$SCRIPT_DIR}"
# Executable (built by build_remote.sh, output under build/remote/)
BIN="${RFAA_BIN:-${PROJ}/build/remote/examples/ppml_train}"
# Python lib dir (server conda/venv lib, provides libpython3.x.so)
PYLIB="${RFAA_PYLIB:-/root/anaconda3/lib}"
# System gcc libstdc++ (avoid conda's older libstdc++ missing GLIBCXX_3.4.30)
# On the server, confirm with `ls /usr/lib/x86_64-linux-gnu/libstdc++.so.6`; set empty if the conda one is new enough
STDCPP_PRELOAD="${RFAA_STDCPP:-/usr/lib/x86_64-linux-gnu/libstdc++.so.6}"

# ---------- Training hyper-parameters (overridable via env) ----------
FULL_TRAIN="${FULL_TRAIN:-true}"
NUM_EPOCHS="${PPML_NUM_EPOCHS:-10}"
LR="${PPML_LR:-1e-4}"
CLIP="${PPML_CLIP_NORM:-0.1}"
ACCUM="${PPML_ACCUM:-4}"
MSA_DEPTH="${PPML_MSA_DEPTH:-512}"
# Stage 2 MSA depth: lowered 512 -> 256 on 2026-09-11.
#   Rationale (local peak calibration peak_CPU_GB ~= 12.9 + 0.102*N, le103 / accum=4 / CPU single backend):
#     N=512 ~= 65GB > server available 55.8GB (OOM'd last round, exit 137); N=256 ~= 39GB (actual alloc 43.9GB) fits.
#   Restore 512: PPML_MULTI_MSA_DEPTH=512 bash remote_fulltrain.sh (confirm server free memory first, or lower PPML_ACCUM).
MULTI_MSA_DEPTH="${PPML_MULTI_MSA_DEPTH:-256}"
USE_CUDA="${PPML_USE_CUDA:-1}"
CUDA_SCHED="${PPML_CUDA_SCHED:-1}"
#  Mixed training reliability: force OP_SCATTER_ADD to fall back to CPU (GPU scatter cross-split race not fixed yet;
#    observed loss blow-up / launch failure on GPU scatter, loss 15.47 normal after CPU fallback).
#    Set PPML_CUDA_NO_SCATTER=0 to disable the fallback (GPU scatter), generally not recommended.
CUDA_NO_SCATTER="${PPML_CUDA_NO_SCATTER:-1}"

# ---------- Log ----------
LOG="remote_fulltrain_$(date +%Y%m%d_%H%M%S).log"

# ---------- Pre-flight checks ----------
if [ ! -x "$BIN" ]; then
    echo "[FATAL] executable not found: $BIN" | tee -a "$LOG"
    echo "        build it on the server first: cd $PROJ && bash build_remote.sh ppml_train" | tee -a "$LOG"
    exit 1
fi
if [ ! -f "$PROJ/data/P04637_alignment.a3m" ]; then
    echo "[FATAL] missing P04637 data (data/P04637_alignment.a3m)" | tee -a "$LOG"
    exit 1
fi
if [ ! -d "$PROJ/data/training_batch_data" ]; then
    echo "[FATAL] missing multi-sample dataset (data/training_batch_data)" | tee -a "$LOG"
    exit 1
fi
# Stage 2 default subset (L<=103): generated by python_scripts/filter_samples_by_len.py
if [ ! -d "$PROJ/data/training_batch_data_le103" ]; then
    echo "[FATAL] missing multi-sample subset dataset (data/training_batch_data_le103, L<=103)" | tee -a "$LOG"
    echo "        run first: python3 python_scripts/filter_samples_by_len.py 103" | tee -a "$LOG"
    exit 1
fi

# ---------- Env export ----------
export FULL_TRAIN PPML_NUM_EPOCHS="$NUM_EPOCHS" PPML_LR="$LR" PPML_CLIP_NORM="$CLIP" \
       PPML_ACCUM="$ACCUM" PPML_MSA_DEPTH="$MSA_DEPTH" \
       PPML_USE_CUDA="$USE_CUDA" PPML_CUDA_SCHED="$CUDA_SCHED" \
       PPML_CUDA_NO_SCATTER="$CUDA_NO_SCATTER"
export LD_LIBRARY_PATH="$PYLIB${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
if [ -n "$STDCPP_PRELOAD" ] && [ -f "$STDCPP_PRELOAD" ]; then
    export LD_PRELOAD="$STDCPP_PRELOAD"
    echo "[env] LD_PRELOAD=$LD_PRELOAD" | tee -a "$LOG"
else
    echo "[env] LD_PRELOAD not set (STDCPP_PRELOAD empty or file missing)" | tee -a "$LOG"
fi
echo "[env] LD_LIBRARY_PATH=$LD_LIBRARY_PATH" | tee -a "$LOG"

echo "============================================================" | tee -a "$LOG"
echo "FULL_TRAIN remote training   log: $LOG" | tee -a "$LOG"
echo "hyper-params: epochs=$NUM_EPOCHS lr=$LR clip=$CLIP accum=$ACCUM msa=stage1-256/stage2-$MULTI_MSA_DEPTH" | tee -a "$LOG"
echo "============================================================" | tee -a "$LOG"

# ---------- Stage 1: single sample P04637 (with templates) ----------
echo "" | tee -a "$LOG"
echo "########## Stage 1/2: P04637 single-sample training (with templates) ##########" | tee -a "$LOG"
# Note: multi-sample mode does not support templates (load_from_files template arg=""),
#       so P04637 uses the single-sample path: template = P04637_template_coords,
#       true coords = P04637_pdbs (multiple PDBs auto-merged).
#       2026-08-28 onward skipped by default (high memory peak; see diag_mem: pair track L^2 dominates, MSA-depth independent);
#       set SKIP_P04637=0 to run stage 1.
if [ "${SKIP_P04637:-1}" = "1" ]; then
    echo "[skip] SKIP_P04637=1, skipping stage 1" | tee -a "$LOG"
else
    cd "$PROJ"
    # disable multi-sample, use single-sample path with templates
    unset PPML_MULTI_SAMPLE
    # stage 1 MSA depth = 256 (overrides global MSA_DEPTH; stage 2 uses MULTI_MSA_DEPTH, default also 256)
    export PPML_MSA_DEPTH=256
    # stage 1 has no timeout: FULL_TRAIN full-size first build + N=256 single epoch can far exceed 1 hour,
    # a hard timeout (exit 124) would kill training and lose all progress (no checkpoint saved). Let it finish naturally.
    echo "[stage1] no timeout, ends when training finishes" | tee -a "$LOG"
    echo "[stage1] progress: tail -f $LOG and watch 'Epoch N/M completed ... loss:' lines" | tee -a "$LOG"
    echo "[stage1] if no Epoch output for a long time, check whether '[FWD-GRAPH] ... build ...' was printed (slow first build is normal)" | tee -a "$LOG"
    "$BIN" \
        "$PROJ/data/P04637_alignment.a3m" \
        "$PROJ/data/P04637.fasta" \
        "$PROJ/data/P04637_pdbs" \
        "$PROJ/data/P04637_template_coords" \
        "" 2>&1 | tee -a "$LOG"
    st1=${PIPESTATUS[0]}
    echo "[stage1] exit=$st1" | tee -a "$LOG"
    if [ "$st1" -ne 0 ] && [ "$st1" -ne 2 ]; then
        echo "[WARN] stage 1 failed (exit=$st1), continuing to stage 2" | tee -a "$LOG"
    fi
fi

# ---------- Stage 2: multi-sample (only L<=103 samples) ----------
echo "" | tee -a "$LOG"
echo "########## Stage 2/2: multi-sample training (training_batch_data_le103, L<=103) ##########" | tee -a "$LOG"
if [ "${SKIP_MULTI:-0}" = "1" ]; then
    echo "[skip] SKIP_MULTI=1, skipping stage 2" | tee -a "$LOG"
else
    cd "$PROJ"
    # stage 2 MSA depth = MULTI_MSA_DEPTH (2026-09-11 lowered global 512 -> 256; see header/var comments)
    export PPML_MSA_DEPTH="$MULTI_MSA_DEPTH"
    echo "[multi] MSA depth = $MULTI_MSA_DEPTH (override via PPML_MULTI_MSA_DEPTH)" | tee -a "$LOG"
    export PPML_MULTI_SAMPLE=1
    # 2026-08-28: use only samples with length <= 103 (pair track L^2 dominates memory; long samples peak high).
    #   The subset dir is generated by python_scripts/filter_samples_by_len.py, contains P62805(L=103)+P62891(L=51).
    #   To switch back to the full set: PPML_DATASET_DIR=$PROJ/data/training_batch_data
    export PPML_DATASET_DIR="${PPML_DATASET_DIR:-$PROJ/data/training_batch_data_le103}"
    echo "[multi] dataset: $PPML_DATASET_DIR" | tee -a "$LOG"
    echo "[multi] no timeout, ends when training finishes" | tee -a "$LOG"
    # stage 2 has no timeout: 10 epochs of multi-sample training take a long time, ends naturally.
    "$BIN" \
        "" "" "" "" "" 2>&1 | tee -a "$LOG"
    st2=${PIPESTATUS[0]}
    echo "[stage2] exit=$st2" | tee -a "$LOG"
    # multi-sample returns 2 when space is insufficient (stops without lowering config)
    if [ "$st2" = "2" ]; then
        echo "[ERROR] multi-sample stopped due to insufficient space (exit 2). Server free memory must be >= PPML_MIN_FREE_GB (default 22)" | tee -a "$LOG"
        exit 2
    fi
fi

echo "" | tee -a "$LOG"
echo "========== All stages finished ==========" | tee -a "$LOG"
echo "log: $LOG" | tee -a "$LOG"
exit 0
